serviceName: gateway_service
grpc:
  queryServicePort: :5003
http:
  port: :5001
  development: true
  basePath: /api/v1
  usersPath: /api/v1/users
  debugHeaders: false
  httpClientDebug: false
  debugErrorsResponse: true
  ignoreLogUrls: [ "metrics" ]
probes:
  readinessPath: /ready
  livenessPath: /live
  port: :3001
  pprof: :6001
  prometheusPath: /metrics
  prometheusPort: :8001
  checkIntervalSeconds: 10
logger:
  level: debug
  devMode: false
  encoder: json
kafka:
  brokers: [ "localhost:9092" ]
  groupID: gateway_consumer
  initTopics: true
kafkaTopics:
  userCreate:
    topicName: user_create
    partitions: 10
    replicationFactor: 1
  userUpdate:
    topicName: user_update
    partitions: 10
    replicationFactor: 1
  userDelete:
    topicName: user_delete
    partitions: 10
    replicationFactor: 1
redis:
  addr: "localhost:6379"
  password: ""
  db: 0
  poolSize: 300
jaeger:
  enable: true
  serviceName: gateway_service
  hostPort: "localhost:6831"
  logSpans: false