DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TABLE IF EXISTS groups_memberships CASCADE;
DROP TABLE IF EXISTS blacklists CASCADE;
DROP EXTENSION IF EXISTS citext CASCADE;